<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-533FUL4V" name="com.icesi.edu.co.jcss.test.TestServiceGame" tests="3" failures="0" timestamp="2020-03-30T23:33:32 COT" time="0.470" errors="1">
  <testcase name="createGameA" time="0.015" classname="com.icesi.edu.co.jcss.test.TestServiceGame">
    <error type="com.icesi.edu.co.jcss.exceptions.ExceptionNotCreateGame" message="Recibe tema pero este no existe">
      <![CDATA[com.icesi.edu.co.jcss.exceptions.ExceptionNotCreateGame: Recibe tema pero este no existe
at com.icesi.edu.co.jcss.services.ServiceGameImpl.saveGame(ServiceGameImpl.java:26)
at com.icesi.edu.co.jcss.test.TestServiceGame.createGameA(TestServiceGame.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createGameA -->
  <testcase name="createGameB" time="0.020" classname="com.icesi.edu.co.jcss.test.TestServiceGame"/>
  <testcase name="createGameC" time="0.435" classname="com.icesi.edu.co.jcss.test.TestServiceGame"/>
</testsuite> <!-- com.icesi.edu.co.jcss.test.TestServiceGame -->
